In [1]:
# Importing Libs
    
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import datetime as dt
import time

from sklearn.dummy import DummyClassifier
from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score, GridSearchCV, cross_validate
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder, LabelEncoder
from sklearn.metrics import confusion_matrix, classification_report,accuracy_score, recall_score
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier


from sklearn.naive_bayes import GaussianNB
#from xgboost import XGBClassifier
#from lightgbm import LGBMClassifier

import warnings



sns.set_theme(style="darkgrid", rc={'figure.figsize':(10,6)})

In [2]:
FRAUD_PATH = "datasets/AIML Dataset.csv"

df = pd.read_csv(FRAUD_PATH)

categorical_features = ['type', 'nameOrig', 'nameDest', 'isFraud', 'isFlaggedFraud']
numerical_features = ['step', 'amount', 'oldbalanceOrg', 'newbalanceOrig', 'oldbalanceDest', 'newbalanceDest']

df['balanceOrigDiff'] = df['newbalanceOrig'] - df['oldbalanceOrg']
df['balanceDestDiff'] = df['newbalanceDest'] - df['oldbalanceDest']

features_model = numerical_features + ['balanceOrigDiff', 'balanceDestDiff', 'isFraud']
df_model = df[features_model]

df_model.head()

,step,amount,oldbalanceOrg,newbalanceOrig,oldbalanceDest,newbalanceDest,balanceOrigDiff,balanceDestDiff,isFraud
0,1,9839.64,170136.0,160296.36,0.0,0.0,-9839.64,0.0,0
1,1,1864.28,21249.0,19384.72,0.0,0.0,-1864.28,0.0,0
2,1,181.00,181.0,0.00,0.0,0.0,-181.00,0.0,1
3,1,181.00,181.0,0.00,21182.0,0.0,-181.00,-21182.0,1
4,1,11668.14,41554.0,29885.86,0.0,0.0,-11668.14,0.0,0

In [3]:
y = df_model["isFraud"]
X = df_model.drop("isFraud", axis = 1)

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, stratify=y, random_state = 42)

In [5]:
scaler =  StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [6]:
stratified_kfold = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

## Random Forest Classifier

In [8]:
models = {
    'Dummy Classifier': DummyClassifier(),
    'Logistic Regression': LogisticRegression(max_iter=1000),
    'Decision Tree': DecisionTreeClassifier(),
    'Naive Bayes': GaussianNB(),
    'KNN': KNeighborsClassifier(),
}

MODEL_EVALUATION_METRICS = [
    "accuracy",
    "balanced_accuracy",
    "f1",
    "precision",
    "recall",
    "roc_auc",
    "average_precision",
    "neg_brier_score",
    "f1_weighted",
]

In [9]:
def train_model(TRAIN_X: pd.DataFrame, 
                TRAIN_Y, 
                MODEL,
                CV):

    scores = cross_validate(
        estimator = MODEL,
        X = TRAIN_X,
        y = TRAIN_Y,
        cv = CV,
        scoring = MODEL_EVALUATION_METRICS,
    )

    return scores

In [10]:
with warnings.catch_warnings():
    warnings.filterwarnings("ignore")

    results = {model_name: train_model(MODEL = classifier, TRAIN_X = X_train, 
                                       TRAIN_Y = y_train, CV = stratified_kfold) for model_name, classifier in models.items()}

In [78]:
def results_to_df(model_results):
    df = pd.DataFrame(model_results)
    df = df.T

    # list of columns
    col_list = df.columns.tolist()

    df = df.explode(col_list)

    df = df.reset_index()

    df[col_list] = df[col_list].astype(float)
    
    df.rename(columns={'index': 'models'}, inplace=True)
    return(df)

In [82]:
df_results = results_to_df(results)
df_results

,models,fit_time,score_time,test_accuracy,test_balanced_accuracy,test_f1,test_precision,test_recall,test_roc_auc,test_average_precision,test_neg_brier_score,test_f1_weighted
0,Dummy Classifier,0.328200,0.940803,0.998709,0.500000,0.000000,0.000000,0.000000,0.500000,0.001291,-0.001289,0.998064
1,Dummy Classifier,0.400971,0.917668,0.998709,0.500000,0.000000,0.000000,0.000000,0.500000,0.001291,-0.001289,0.998064
2,Dummy Classifier,0.331922,0.860094,0.998709,0.500000,0.000000,0.000000,0.000000,0.500000,0.001291,-0.001289,0.998064
3,Dummy Classifier,0.375432,0.954767,0.998709,0.500000,0.000000,0.000000,0.000000,0.500000,0.001291,-0.001289,0.998064
4,Dummy Classifier,0.436856,1.001108,0.998710,0.500000,0.000000,0.000000,0.000000,0.500000,0.001290,-0.001288,0.998066
5,Logistic Regression,3.264693,1.203579,0.999248,0.739525,0.621896,0.885852,0.479130,0.962167,0.609952,-0.000694,0.999136
6,Logistic Regression,3.643543,1.395863,0.999233,0.734307,0.612152,0.882160,0.468696,0.958897,0.612170,-0.000695,0.999116
7,Logistic Regression,2.876654,1.143718,0.999273,0.746919,0.636771,0.895899,0.493913,0.954672,0.619977,-0.000670,0.999167
8,Logistic Regression,3.162219,1.146654,0.999255,0.738660,0.623156,0.897059,0.477391,0.955283,0.616341,-0.000681,0.999141
9,Logistic Regression,2.936168,1.233847,0.999223,0.737113,0.611672,0.860979,0.474326,0.959104,0.604394,-0.000710,0.999111
10,Decision Tree,80.773461,0.906219,0.999603,0.917299,0.844327,0.854093,0.834783,0.917299,0.713195,-0.000397,0.999600
11,Decision Tree,67.793939,0.994065,0.999578,0.906431,0.832591,0.853102,0.813043,0.906431,0.693851,-0.000422,0.999573
12,Decision Tree,73.003066,0.980591,0.999568,0.912505,0.831362,0.837599,0.825217,0.912505,0.691427,-0.000432,0.999566
13,Decision Tree,77.325337,0.987227,0.999623,0.922520,0.852632,0.860177,0.845217,0.922520,0.727236,-0.000377,0.999621
14,Decision Tree,84.652021,1.001765,0.999541,0.908939,0.821319,0.824561,0.818103,0.908939,0.674811,-0.000459,0.999540
15,Naive Bayes,0.946962,1.606373,0.989491,0.732904,0.104639,0.058786,0.475652,0.913220,0.073395,-0.009695,0.993565
16,Naive Bayes,0.937997,1.560047,0.989582,0.730778,0.104593,0.058824,0.471304,0.906049,0.072677,-0.009635,0.993611
17,Naive Bayes,0.913996,1.570086,0.989731,0.749090,0.113233,0.063721,0.507826,0.911558,0.081277,-0.009471,0.993698
18,Naive Bayes,0.947390,1.596509,0.992490,0.741352,0.144063,0.084458,0.489565,0.911122,0.107118,-0.006861,0.995128
19,Naive Bayes,0.959999,1.531811,0.989360,0.731306,0.102802,0.057674,0.472585,0.901774,0.065533,-0.009881,0.993498
20,KNN,20.922524,213.182215,0.999406,0.804738,0.726049,0.897567,0.609565,0.877114,0.670851,-0.000551,0.999349
21,KNN,21.232722,212.513744,0.999398,0.807773,0.725410,0.882793,0.615652,0.876231,0.664793,-0.000561,0.999345
22,KNN,21.003864,212.377483,0.999424,0.817773,0.740253,0.886061,0.635652,0.883209,0.689738,-0.000530,0.999377
23,KNN,19.975666,216.379365,0.999429,0.812565,0.738572,0.902133,0.625217,0.873204,0.671231,-0.000549,0.999377
24,KNN,20.231233,214.380419,0.999396,0.808039,0.724667,0.879503,0.616188,0.873514,0.668293,-0.000560,0.999343

In [100]:
df_results.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   models                  25 non-null     object
 1   fit_time                25 non-null     float64
 2   score_time              25 non-null     float64
 3   test_accuracy           25 non-null     float64
 4   test_balanced_accuracy  25 non-null     float64
 5   test_f1                 25 non-null     float64
 6   test_precision          25 non-null     float64
 7   test_recall             25 non-null     float64
 8   test_roc_auc            25 non-null     float64
 9   test_average_precision  25 non-null     float64
 10  test_neg_brier_score    25 non-null     float64
 11  test_f1_weighted        25 non-null     float64
dtypes: float64(11), object(1)
memory usage: 2.5+ KB

In [114]:
df_results[['test_balanced_accuracy','test_accuracy']].mean()

test_balanced_accuracy    0.740022
test_accuracy             0.997416
dtype: float64

In [118]:
df_results.groupby("models").mean().sort_values(
    "test_average_precision"
)

,fit_time,score_time,test_accuracy,test_balanced_accuracy,test_f1,test_precision,test_recall,test_roc_auc,test_average_precision,test_neg_brier_score,test_f1_weighted
models,,,,,,,,,,,
Dummy Classifier,0.374676,0.934888,0.998709,0.500000,0.000000,0.000000,0.000000,0.500000,0.001291,-0.001289,0.998064
Naive Bayes,0.941269,1.572965,0.990131,0.737086,0.113866,0.064692,0.483387,0.908744,0.080000,-0.009109,0.993900
Logistic Regression,3.176655,1.224732,0.999246,0.739305,0.621129,0.884390,0.478691,0.958025,0.612567,-0.000690,0.999134
KNN,20.673202,213.766645,0.999411,0.810178,0.730990,0.889611,0.620455,0.876654,0.672981,-0.000550,0.999358
Decision Tree,76.709565,0.973974,0.999582,0.913539,0.836446,0.845906,0.827273,0.913539,0.700104,-0.000418,0.999580