# 2.2 - Modeling - Fine Tunning

Esta etapa é uma continuação da anterior, **2.1 - Modeling.ipynb**, que foi utilizada para se definir o melhor modelo para a análise em questão com base nos quesitos: tempo, recall e xxx (test_average_precision).

A partir de agora será efetuado o **Fine Tunning** para obtermos o melhor modelo, então exportar este utilizando a biblioteca `joblib` e então, aplicar aos testes na seção `2.3 - Modeling_Test`

## Importing Libs

In [1]:
# Importing Libs
    
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_theme(style="darkgrid", rc={'figure.figsize':(10,6)})

from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score, GridSearchCV, cross_validate
from sklearn.preprocessing import StandardScaler, OneHotEncoder, LabelEncoder
from sklearn.metrics import confusion_matrix, classification_report,accuracy_score, recall_score

from xgboost import XGBClassifier

import warnings

## Importing Dataset and Feature Engeneering

Nesta etapa:
- Foi importado o dataset
- Foi utilizdo os valores criados na seção **1 - EDA.ipynb**, `balanceOrigDiff` e `balanceDestDiff`
- Foram removidos valores que não seriam relevanesna previsão

In [3]:
FRAUD_PATH = "datasets/AIML Dataset.csv"

df = pd.read_csv(FRAUD_PATH)

categorical_features = ['type', 'nameOrig', 'nameDest', 'isFraud', 'isFlaggedFraud']
numerical_features = ['step', 'amount', 'oldbalanceOrg', 'newbalanceOrig', 'oldbalanceDest', 'newbalanceDest']

df['balanceOrigDiff'] = df['newbalanceOrig'] - df['oldbalanceOrg']
df['balanceDestDiff'] = df['newbalanceDest'] - df['oldbalanceDest']

features_model = numerical_features + ['balanceOrigDiff', 'balanceDestDiff', 'isFraud']
df_model = df[features_model]

df_model.head()

,step,amount,oldbalanceOrg,newbalanceOrig,oldbalanceDest,newbalanceDest,balanceOrigDiff,balanceDestDiff,isFraud
0,1,9839.64,170136.0,160296.36,0.0,0.0,-9839.64,0.0,0
1,1,1864.28,21249.0,19384.72,0.0,0.0,-1864.28,0.0,0
2,1,181.00,181.0,0.00,0.0,0.0,-181.00,0.0,1
3,1,181.00,181.0,0.00,21182.0,0.0,-181.00,-21182.0,1
4,1,11668.14,41554.0,29885.86,0.0,0.0,-11668.14,0.0,0

## Train Test Split

A divisão dos dados foi feita da seguinte maneira:
- Foi separada a classe de interesse (`isFraud`) como **y** e as demais como **X**
- A divisão foi feita em uma proporção 70-30 devido ao elevado volume de dados
- Foi utilizado o hiperparâmetro `stratify` de modo a se manter a proporção de classes positivas e negativas tanto para o test set quanto para o training set
- Como não se tem valores categórigos, apenas foi necessário se fazer os `StandardScaler`

In [4]:
y = df_model["isFraud"]
X = df_model.drop("isFraud", axis = 1)

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, stratify=y, random_state = 42)

In [6]:
scaler =  StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

`StratifiedKFold` é utilizado dividindo os dados em K partes (folds) para fazer validação cruzada, mantendo a proporção das classes em cada fold.
Ou seja, em cada Cross-Validation é garantido que cada fold tenha representatividade das classes.

In [7]:
stratified_kfold = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

## Fine Tunning

In [8]:
MODEL_EVALUATION_METRICS = [
    "accuracy",
    "balanced_accuracy",
    "f1",
    "precision",
    "recall",
    "roc_auc",
    "average_precision",
    "neg_brier_score",
    "f1_weighted",
]

In [11]:
# Model Instance
xgb = XGBClassifier(use_label_encoder=False, 
                    eval_metric='logloss', 
                    random_state=42)

# Hyperparameters Dict
param_grid = {
    'n_estimators': [350, 400],
    'max_depth': [9, 12],
    'learning_rate': [0.1, 0.3],
    'subsample': [0.8, 0.9],
    'colsample_bytree': [0.9, 1]
}

In [12]:
# Instância do GridSearch
grid_search = GridSearchCV(
    estimator = xgb,
    param_grid = param_grid,
    scoring = MODEL_EVALUATION_METRICS,
    refit="average_precision",
    cv = stratified_kfold,
    n_jobs = 1,
    verbose = 2
)

In [19]:
# Ajustando o modelo com os dados de treino
with warnings.catch_warnings():
    warnings.filterwarnings("ignore")
    
    grid_search.fit(X_train, y_train)

Fitting 5 folds for each of 32 candidates, totalling 160 fits
[CV] END colsample_bytree=0.9, learning_rate=0.1, max_depth=9, n_estimators=350, subsample=0.8; total time=  54.8s
[CV] END colsample_bytree=0.9, learning_rate=0.1, max_depth=9, n_estimators=350, subsample=0.8; total time=  59.0s
[CV] END colsample_bytree=0.9, learning_rate=0.1, max_depth=9, n_estimators=350, subsample=0.8; total time=  56.7s
[CV] END colsample_bytree=0.9, learning_rate=0.1, max_depth=9, n_estimators=350, subsample=0.8; total time=  58.2s
[CV] END colsample_bytree=0.9, learning_rate=0.1, max_depth=9, n_estimators=350, subsample=0.8; total time=  59.0s
[CV] END colsample_bytree=0.9, learning_rate=0.1, max_depth=9, n_estimators=350, subsample=0.9; total time= 1.1min
[CV] END colsample_bytree=0.9, learning_rate=0.1, max_depth=9, n_estimators=350, subsample=0.9; total time= 1.1min
[CV] END colsample_bytree=0.9, learning_rate=0.1, max_depth=9, n_estimators=350, subsample=0.9; total time=  57.2s
[CV] END colsample_bytree=0.9, learning_rate=0.1, max_depth=9, n_estimators=350, subsample=0.9; total time=  56.1s
[CV] END colsample_bytree=0.9, learning_rate=0.1, max_depth=9, n_estimators=350, subsample=0.9; total time=  56.5s
[CV] END colsample_bytree=0.9, learning_rate=0.1, max_depth=9, n_estimators=400, subsample=0.8; total time= 1.1min
[CV] END colsample_bytree=0.9, learning_rate=0.1, max_depth=9, n_estimators=400, subsample=0.8; total time= 1.1min
[CV] END colsample_bytree=0.9, learning_rate=0.1, max_depth=9, n_estimators=400, subsample=0.8; total time= 1.3min
[CV] END colsample_bytree=0.9, learning_rate=0.1, max_depth=9, n_estimators=400, subsample=0.8; total time= 1.3min
[CV] END colsample_bytree=0.9, learning_rate=0.1, max_depth=9, n_estimators=400, subsample=0.8; total time= 1.2min
[CV] END colsample_bytree=0.9, learning_rate=0.1, max_depth=9, n_estimators=400, subsample=0.9; total time= 1.1min
[CV] END colsample_bytree=0.9, learning_rate=0.1, max_depth=9, n_estimators=400, subsample=0.9; total time=  53.7s
[CV] END colsample_bytree=0.9, learning_rate=0.1, max_depth=9, n_estimators=400, subsample=0.9; total time=  54.4s
[CV] END colsample_bytree=0.9, learning_rate=0.1, max_depth=9, n_estimators=400, subsample=0.9; total time=  57.5s
[CV] END colsample_bytree=0.9, learning_rate=0.1, max_depth=9, n_estimators=400, subsample=0.9; total time=  57.4s
[CV] END colsample_bytree=0.9, learning_rate=0.1, max_depth=12, n_estimators=350, subsample=0.8; total time=  56.8s
[CV] END colsample_bytree=0.9, learning_rate=0.1, max_depth=12, n_estimators=350, subsample=0.8; total time=  55.2s
[CV] END colsample_bytree=0.9, learning_rate=0.1, max_depth=12, n_estimators=350, subsample=0.8; total time=  51.9s
[CV] END colsample_bytree=0.9, learning_rate=0.1, max_depth=12, n_estimators=350, subsample=0.8; total time=  51.3s
[CV] END colsample_bytree=0.9, learning_rate=0.1, max_depth=12, n_estimators=350, subsample=0.8; total time=  51.3s
[CV] END colsample_bytree=0.9, learning_rate=0.1, max_depth=12, n_estimators=350, subsample=0.9; total time=  54.8s
[CV] END colsample_bytree=0.9, learning_rate=0.1, max_depth=12, n_estimators=350, subsample=0.9; total time=  56.9s
[CV] END colsample_bytree=0.9, learning_rate=0.1, max_depth=12, n_estimators=350, subsample=0.9; total time=  56.0s
[CV] END colsample_bytree=0.9, learning_rate=0.1, max_depth=12, n_estimators=350, subsample=0.9; total time=  56.9s
[CV] END colsample_bytree=0.9, learning_rate=0.1, max_depth=12, n_estimators=350, subsample=0.9; total time=  57.1s
[CV] END colsample_bytree=0.9, learning_rate=0.1, max_depth=12, n_estimators=400, subsample=0.8; total time= 1.1min
[CV] END colsample_bytree=0.9, learning_rate=0.1, max_depth=12, n_estimators=400, subsample=0.8; total time= 1.0min
[CV] END colsample_bytree=0.9, learning_rate=0.1, max_depth=12, n_estimators=400, subsample=0.8; total time= 1.0min
[CV] END colsample_bytree=0.9, learning_rate=0.1, max_depth=12, n_estimators=400, subsample=0.8; total time= 1.0min
[CV] END colsample_bytree=0.9, learning_rate=0.1, max_depth=12, n_estimators=400, subsample=0.8; total time= 1.0min
[CV] END colsample_bytree=0.9, learning_rate=0.1, max_depth=12, n_estimators=400, subsample=0.9; total time= 1.0min
[CV] END colsample_bytree=0.9, learning_rate=0.1, max_depth=12, n_estimators=400, subsample=0.9; total time= 1.2min
[CV] END colsample_bytree=0.9, learning_rate=0.1, max_depth=12, n_estimators=400, subsample=0.9; total time= 1.1min
[CV] END colsample_bytree=0.9, learning_rate=0.1, max_depth=12, n_estimators=400, subsample=0.9; total time= 1.2min
[CV] END colsample_bytree=0.9, learning_rate=0.1, max_depth=12, n_estimators=400, subsample=0.9; total time= 1.0min
[CV] END colsample_bytree=0.9, learning_rate=0.3, max_depth=9, n_estimators=350, subsample=0.8; total time= 1.0min
[CV] END colsample_bytree=0.9, learning_rate=0.3, max_depth=9, n_estimators=350, subsample=0.8; total time= 1.1min
[CV] END colsample_bytree=0.9, learning_rate=0.3, max_depth=9, n_estimators=350, subsample=0.8; total time= 1.1min
[CV] END colsample_bytree=0.9, learning_rate=0.3, max_depth=9, n_estimators=350, subsample=0.8; total time= 1.1min
[CV] END colsample_bytree=0.9, learning_rate=0.3, max_depth=9, n_estimators=350, subsample=0.8; total time=  54.2s
[CV] END colsample_bytree=0.9, learning_rate=0.3, max_depth=9, n_estimators=350, subsample=0.9; total time=  49.1s
[CV] END colsample_bytree=0.9, learning_rate=0.3, max_depth=9, n_estimators=350, subsample=0.9; total time=  50.2s
[CV] END colsample_bytree=0.9, learning_rate=0.3, max_depth=9, n_estimators=350, subsample=0.9; total time=  51.2s
[CV] END colsample_bytree=0.9, learning_rate=0.3, max_depth=9, n_estimators=350, subsample=0.9; total time=  49.4s
[CV] END colsample_bytree=0.9, learning_rate=0.3, max_depth=9, n_estimators=350, subsample=0.9; total time=  50.2s
[CV] END colsample_bytree=0.9, learning_rate=0.3, max_depth=9, n_estimators=400, subsample=0.8; total time=  57.9s
[CV] END colsample_bytree=0.9, learning_rate=0.3, max_depth=9, n_estimators=400, subsample=0.8; total time=  58.5s
[CV] END colsample_bytree=0.9, learning_rate=0.3, max_depth=9, n_estimators=400, subsample=0.8; total time=  57.6s
[CV] END colsample_bytree=0.9, learning_rate=0.3, max_depth=9, n_estimators=400, subsample=0.8; total time=  58.5s
[CV] END colsample_bytree=0.9, learning_rate=0.3, max_depth=9, n_estimators=400, subsample=0.8; total time=  58.7s
[CV] END colsample_bytree=0.9, learning_rate=0.3, max_depth=9, n_estimators=400, subsample=0.9; total time=  56.9s
[CV] END colsample_bytree=0.9, learning_rate=0.3, max_depth=9, n_estimators=400, subsample=0.9; total time=  57.4s
[CV] END colsample_bytree=0.9, learning_rate=0.3, max_depth=9, n_estimators=400, subsample=0.9; total time=  56.5s
[CV] END colsample_bytree=0.9, learning_rate=0.3, max_depth=9, n_estimators=400, subsample=0.9; total time=  55.8s
[CV] END colsample_bytree=0.9, learning_rate=0.3, max_depth=9, n_estimators=400, subsample=0.9; total time= 1.1min
[CV] END colsample_bytree=0.9, learning_rate=0.3, max_depth=12, n_estimators=350, subsample=0.8; total time= 1.1min
[CV] END colsample_bytree=0.9, learning_rate=0.3, max_depth=12, n_estimators=350, subsample=0.8; total time= 1.0min
[CV] END colsample_bytree=0.9, learning_rate=0.3, max_depth=12, n_estimators=350, subsample=0.8; total time=  56.2s
[CV] END colsample_bytree=0.9, learning_rate=0.3, max_depth=12, n_estimators=350, subsample=0.8; total time=  57.1s
[CV] END colsample_bytree=0.9, learning_rate=0.3, max_depth=12, n_estimators=350, subsample=0.8; total time=  55.2s
[CV] END colsample_bytree=0.9, learning_rate=0.3, max_depth=12, n_estimators=350, subsample=0.9; total time=  55.8s
[CV] END colsample_bytree=0.9, learning_rate=0.3, max_depth=12, n_estimators=350, subsample=0.9; total time=  55.6s
[CV] END colsample_bytree=0.9, learning_rate=0.3, max_depth=12, n_estimators=350, subsample=0.9; total time=  56.7s
[CV] END colsample_bytree=0.9, learning_rate=0.3, max_depth=12, n_estimators=350, subsample=0.9; total time=  55.7s
[CV] END colsample_bytree=0.9, learning_rate=0.3, max_depth=12, n_estimators=350, subsample=0.9; total time= 1.0min
[CV] END colsample_bytree=0.9, learning_rate=0.3, max_depth=12, n_estimators=400, subsample=0.8; total time= 1.1min
[CV] END colsample_bytree=0.9, learning_rate=0.3, max_depth=12, n_estimators=400, subsample=0.8; total time= 1.1min
[CV] END colsample_bytree=0.9, learning_rate=0.3, max_depth=12, n_estimators=400, subsample=0.8; total time= 1.1min
[CV] END colsample_bytree=0.9, learning_rate=0.3, max_depth=12, n_estimators=400, subsample=0.8; total time= 1.1min
[CV] END colsample_bytree=0.9, learning_rate=0.3, max_depth=12, n_estimators=400, subsample=0.8; total time= 1.1min
[CV] END colsample_bytree=0.9, learning_rate=0.3, max_depth=12, n_estimators=400, subsample=0.9; total time= 1.1min
[CV] END colsample_bytree=0.9, learning_rate=0.3, max_depth=12, n_estimators=400, subsample=0.9; total time= 1.1min
[CV] END colsample_bytree=0.9, learning_rate=0.3, max_depth=12, n_estimators=400, subsample=0.9; total time= 1.1min
[CV] END colsample_bytree=0.9, learning_rate=0.3, max_depth=12, n_estimators=400, subsample=0.9; total time= 1.1min
[CV] END colsample_bytree=0.9, learning_rate=0.3, max_depth=12, n_estimators=400, subsample=0.9; total time= 1.1min
[CV] END colsample_bytree=1, learning_rate=0.1, max_depth=9, n_estimators=350, subsample=0.8; total time=  48.6s
[CV] END colsample_bytree=1, learning_rate=0.1, max_depth=9, n_estimators=350, subsample=0.8; total time=  49.6s
[CV] END colsample_bytree=1, learning_rate=0.1, max_depth=9, n_estimators=350, subsample=0.8; total time=  48.4s
[CV] END colsample_bytree=1, learning_rate=0.1, max_depth=9, n_estimators=350, subsample=0.8; total time=  48.5s
[CV] END colsample_bytree=1, learning_rate=0.1, max_depth=9, n_estimators=350, subsample=0.8; total time=  49.0s
[CV] END colsample_bytree=1, learning_rate=0.1, max_depth=9, n_estimators=350, subsample=0.9; total time=  47.4s
[CV] END colsample_bytree=1, learning_rate=0.1, max_depth=9, n_estimators=350, subsample=0.9; total time=  48.3s
[CV] END colsample_bytree=1, learning_rate=0.1, max_depth=9, n_estimators=350, subsample=0.9; total time=  46.6s
[CV] END colsample_bytree=1, learning_rate=0.1, max_depth=9, n_estimators=350, subsample=0.9; total time=  48.1s
[CV] END colsample_bytree=1, learning_rate=0.1, max_depth=9, n_estimators=350, subsample=0.9; total time=  47.3s
[CV] END colsample_bytree=1, learning_rate=0.1, max_depth=9, n_estimators=400, subsample=0.8; total time=  56.3s
[CV] END colsample_bytree=1, learning_rate=0.1, max_depth=9, n_estimators=400, subsample=0.8; total time= 1.1min
[CV] END colsample_bytree=1, learning_rate=0.1, max_depth=9, n_estimators=400, subsample=0.8; total time= 1.1min
[CV] END colsample_bytree=1, learning_rate=0.1, max_depth=9, n_estimators=400, subsample=0.8; total time= 1.1min
[CV] END colsample_bytree=1, learning_rate=0.1, max_depth=9, n_estimators=400, subsample=0.8; total time= 1.2min
[CV] END colsample_bytree=1, learning_rate=0.1, max_depth=9, n_estimators=400, subsample=0.9; total time= 1.1min
[CV] END colsample_bytree=1, learning_rate=0.1, max_depth=9, n_estimators=400, subsample=0.9; total time= 1.1min
[CV] END colsample_bytree=1, learning_rate=0.1, max_depth=9, n_estimators=400, subsample=0.9; total time= 1.1min
[CV] END colsample_bytree=1, learning_rate=0.1, max_depth=9, n_estimators=400, subsample=0.9; total time= 1.1min
[CV] END colsample_bytree=1, learning_rate=0.1, max_depth=9, n_estimators=400, subsample=0.9; total time= 1.0min
[CV] END colsample_bytree=1, learning_rate=0.1, max_depth=12, n_estimators=350, subsample=0.8; total time= 1.0min
[CV] END colsample_bytree=1, learning_rate=0.1, max_depth=12, n_estimators=350, subsample=0.8; total time= 1.0min
[CV] END colsample_bytree=1, learning_rate=0.1, max_depth=12, n_estimators=350, subsample=0.8; total time= 1.1min
[CV] END colsample_bytree=1, learning_rate=0.1, max_depth=12, n_estimators=350, subsample=0.8; total time= 1.1min
[CV] END colsample_bytree=1, learning_rate=0.1, max_depth=12, n_estimators=350, subsample=0.8; total time= 1.1min
[CV] END colsample_bytree=1, learning_rate=0.1, max_depth=12, n_estimators=350, subsample=0.9; total time= 1.0min
[CV] END colsample_bytree=1, learning_rate=0.1, max_depth=12, n_estimators=350, subsample=0.9; total time= 1.0min
[CV] END colsample_bytree=1, learning_rate=0.1, max_depth=12, n_estimators=350, subsample=0.9; total time= 1.0min
[CV] END colsample_bytree=1, learning_rate=0.1, max_depth=12, n_estimators=350, subsample=0.9; total time= 1.0min
[CV] END colsample_bytree=1, learning_rate=0.1, max_depth=12, n_estimators=350, subsample=0.9; total time= 1.0min
[CV] END colsample_bytree=1, learning_rate=0.1, max_depth=12, n_estimators=400, subsample=0.8; total time= 1.2min
[CV] END colsample_bytree=1, learning_rate=0.1, max_depth=12, n_estimators=400, subsample=0.8; total time= 1.2min
[CV] END colsample_bytree=1, learning_rate=0.1, max_depth=12, n_estimators=400, subsample=0.8; total time= 1.2min
[CV] END colsample_bytree=1, learning_rate=0.1, max_depth=12, n_estimators=400, subsample=0.8; total time= 1.2min
[CV] END colsample_bytree=1, learning_rate=0.1, max_depth=12, n_estimators=400, subsample=0.8; total time= 1.2min
[CV] END colsample_bytree=1, learning_rate=0.1, max_depth=12, n_estimators=400, subsample=0.9; total time= 1.2min
[CV] END colsample_bytree=1, learning_rate=0.1, max_depth=12, n_estimators=400, subsample=0.9; total time= 1.2min
[CV] END colsample_bytree=1, learning_rate=0.1, max_depth=12, n_estimators=400, subsample=0.9; total time= 1.2min
[CV] END colsample_bytree=1, learning_rate=0.1, max_depth=12, n_estimators=400, subsample=0.9; total time= 1.2min
[CV] END colsample_bytree=1, learning_rate=0.1, max_depth=12, n_estimators=400, subsample=0.9; total time= 1.2min
[CV] END colsample_bytree=1, learning_rate=0.3, max_depth=9, n_estimators=350, subsample=0.8; total time= 1.0min
[CV] END colsample_bytree=1, learning_rate=0.3, max_depth=9, n_estimators=350, subsample=0.8; total time=  59.9s
[CV] END colsample_bytree=1, learning_rate=0.3, max_depth=9, n_estimators=350, subsample=0.8; total time= 1.0min
[CV] END colsample_bytree=1, learning_rate=0.3, max_depth=9, n_estimators=350, subsample=0.8; total time= 1.0min
[CV] END colsample_bytree=1, learning_rate=0.3, max_depth=9, n_estimators=350, subsample=0.8; total time= 1.0min
[CV] END colsample_bytree=1, learning_rate=0.3, max_depth=9, n_estimators=350, subsample=0.9; total time= 1.0min
[CV] END colsample_bytree=1, learning_rate=0.3, max_depth=9, n_estimators=350, subsample=0.9; total time=  59.6s
[CV] END colsample_bytree=1, learning_rate=0.3, max_depth=9, n_estimators=350, subsample=0.9; total time=  59.0s
[CV] END colsample_bytree=1, learning_rate=0.3, max_depth=9, n_estimators=350, subsample=0.9; total time= 1.0min
[CV] END colsample_bytree=1, learning_rate=0.3, max_depth=9, n_estimators=350, subsample=0.9; total time=  59.7s
[CV] END colsample_bytree=1, learning_rate=0.3, max_depth=9, n_estimators=400, subsample=0.8; total time= 1.2min
[CV] END colsample_bytree=1, learning_rate=0.3, max_depth=9, n_estimators=400, subsample=0.8; total time= 1.1min
[CV] END colsample_bytree=1, learning_rate=0.3, max_depth=9, n_estimators=400, subsample=0.8; total time= 1.2min
[CV] END colsample_bytree=1, learning_rate=0.3, max_depth=9, n_estimators=400, subsample=0.8; total time= 1.2min
[CV] END colsample_bytree=1, learning_rate=0.3, max_depth=9, n_estimators=400, subsample=0.8; total time= 1.2min
[CV] END colsample_bytree=1, learning_rate=0.3, max_depth=9, n_estimators=400, subsample=0.9; total time= 1.1min
[CV] END colsample_bytree=1, learning_rate=0.3, max_depth=9, n_estimators=400, subsample=0.9; total time= 1.1min
[CV] END colsample_bytree=1, learning_rate=0.3, max_depth=9, n_estimators=400, subsample=0.9; total time= 1.1min
[CV] END colsample_bytree=1, learning_rate=0.3, max_depth=9, n_estimators=400, subsample=0.9; total time= 1.1min
[CV] END colsample_bytree=1, learning_rate=0.3, max_depth=9, n_estimators=400, subsample=0.9; total time= 1.1min
[CV] END colsample_bytree=1, learning_rate=0.3, max_depth=12, n_estimators=350, subsample=0.8; total time= 1.1min
[CV] END colsample_bytree=1, learning_rate=0.3, max_depth=12, n_estimators=350, subsample=0.8; total time= 1.1min
[CV] END colsample_bytree=1, learning_rate=0.3, max_depth=12, n_estimators=350, subsample=0.8; total time= 1.1min
[CV] END colsample_bytree=1, learning_rate=0.3, max_depth=12, n_estimators=350, subsample=0.8; total time= 1.1min
[CV] END colsample_bytree=1, learning_rate=0.3, max_depth=12, n_estimators=350, subsample=0.8; total time= 1.1min
[CV] END colsample_bytree=1, learning_rate=0.3, max_depth=12, n_estimators=350, subsample=0.9; total time= 1.1min
[CV] END colsample_bytree=1, learning_rate=0.3, max_depth=12, n_estimators=350, subsample=0.9; total time= 1.1min
[CV] END colsample_bytree=1, learning_rate=0.3, max_depth=12, n_estimators=350, subsample=0.9; total time= 1.1min
[CV] END colsample_bytree=1, learning_rate=0.3, max_depth=12, n_estimators=350, subsample=0.9; total time= 1.1min
[CV] END colsample_bytree=1, learning_rate=0.3, max_depth=12, n_estimators=350, subsample=0.9; total time= 1.1min
[CV] END colsample_bytree=1, learning_rate=0.3, max_depth=12, n_estimators=400, subsample=0.8; total time= 1.3min
[CV] END colsample_bytree=1, learning_rate=0.3, max_depth=12, n_estimators=400, subsample=0.8; total time= 1.3min
[CV] END colsample_bytree=1, learning_rate=0.3, max_depth=12, n_estimators=400, subsample=0.8; total time= 1.3min
[CV] END colsample_bytree=1, learning_rate=0.3, max_depth=12, n_estimators=400, subsample=0.8; total time= 1.3min
[CV] END colsample_bytree=1, learning_rate=0.3, max_depth=12, n_estimators=400, subsample=0.8; total time= 1.3min
[CV] END colsample_bytree=1, learning_rate=0.3, max_depth=12, n_estimators=400, subsample=0.9; total time= 1.3min
[CV] END colsample_bytree=1, learning_rate=0.3, max_depth=12, n_estimators=400, subsample=0.9; total time= 1.3min
[CV] END colsample_bytree=1, learning_rate=0.3, max_depth=12, n_estimators=400, subsample=0.9; total time= 1.3min
[CV] END colsample_bytree=1, learning_rate=0.3, max_depth=12, n_estimators=400, subsample=0.9; total time= 1.3min
[CV] END colsample_bytree=1, learning_rate=0.3, max_depth=12, n_estimators=400, subsample=0.9; total time= 1.3min

In [27]:
# Resultados
print("best parameters:", grid_search.best_params_)
print("best score:", grid_search.best_score_)

best parameters: {'colsample_bytree': 1, 'learning_rate': 0.1, 'max_depth': 9, 'n_estimators': 400, 'subsample': 0.9}
best score: 0.9377652170875471

In [29]:
import joblib
filename = 'best_xgb_model.joblib'

joblib.dump(grid_search.best_estimator_, filename)

['best_xgb_model.joblib']

In [31]:
def get_mean_and_std_from_grid_search_best_estimator(
    grid_search: GridSearchCV,
) -> pd.DataFrame:
    """
    Get mean and std scores for the best estimator from a GridSearchCV object.

    Parameters
    ----------
    grid_search : GridSearchCV
        Fitted GridSearchCV object.

    Returns
    -------
    pd.DataFrame
        DataFrame with mean and std scores for the best estimator
    """
    best_estimator_index = grid_search.best_index_
    cv_results = grid_search.cv_results_

    mean_scores = {}
    std_scores = {}

    for metric in grid_search.scoring:
        mean_scores[metric] = cv_results[f"mean_test_{metric}"][best_estimator_index]
        std_scores[metric] = cv_results[f"std_test_{metric}"][best_estimator_index]

    # create dataframe with mean and std scores for each metric
    # metric | mean | std
    df_mean_scores = pd.DataFrame(mean_scores, index=["score"]).T
    df_std_scores = pd.DataFrame(std_scores, index=["std"]).T
    df_mean_std_scores = pd.concat([df_mean_scores, df_std_scores], axis=1)

    return df_mean_std_scores

In [33]:
get_mean_and_std_from_grid_search_best_estimator(grid_search)

                      score       std
accuracy           0.999683  0.000015
balanced_accuracy  0.907422  0.004446
f1                 0.869020  0.006452
precision          0.930856  0.005120
recall             0.814921  0.008890
roc_auc            0.999287  0.000353
average_precision  0.937765  0.003374
neg_brier_score   -0.000251  0.000011
f1_weighted        0.999672  0.000016

In [35]:
grid_search.cv_results_

{'mean_fit_time': array([53.31491632, 55.37812448, 67.56757717, 54.42177854, 49.70153923,
        52.40325956, 58.80922794, 62.27135253, 57.76403174, 46.80388918,
        54.67477503, 55.03685794, 55.66709189, 53.48436708, 62.11786761,
        61.74675622, 45.68576899, 44.46430721, 62.94206338, 60.5535749 ,
        59.44342594, 57.40618362, 69.64557047, 67.9125947 , 57.81477795,
        56.05484052, 65.77690001, 62.9464437 , 61.54788632, 62.03939037,
        72.21754751, 72.32268019]),
 'std_fit_time': array([1.5466871 , 3.8700911 , 4.93757872, 4.64517745, 2.08777944,
        0.78174394, 2.14599828, 4.64325005, 3.45080288, 0.73028745,
        0.37678778, 3.9021503 , 4.83778963, 2.56622159, 0.62788901,
        0.75016062, 0.41334721, 0.60003931, 5.42561043, 1.31687321,
        0.90140927, 0.63407051, 0.42903607, 0.45847128, 1.11483304,
        0.51337026, 1.19735887, 0.72081822, 0.5035381 , 1.09017284,
        0.75339476, 0.40067121]),
 'mean_score_time': array([4.30240874, 4.79894128, 4.9224936 , 3.70757451, 3.70994964,
        4.02399244, 4.05198627, 4.56337476, 3.90953379, 3.33144474,
        3.67949095, 3.71880212, 3.96009645, 3.9081985 , 4.2666677 ,
        4.17946978, 3.22422452, 3.19365821, 4.06900892, 4.05043745,
        4.12089109, 4.10784411, 4.65486765, 4.6224853 , 3.7945025 ,
        3.82824192, 4.18949594, 4.13447638, 4.26583209, 4.36367068,
        4.73897057, 4.93674226]),
 'std_score_time': array([0.12345194, 0.8047067 , 0.55059179, 0.13452721, 0.22721235,
        0.18612272, 0.03699472, 0.33262167, 0.33111751, 0.04416359,
        0.03513809, 0.13497745, 0.17093944, 0.1788161 , 0.07798087,
        0.03842521, 0.05853073, 0.02139301, 0.0929048 , 0.09385047,
        0.07261675, 0.12011237, 0.07351608, 0.11704231, 0.05632328,
        0.1474783 , 0.06626062, 0.03866132, 0.09569583, 0.14518778,
        0.16605146, 0.19777336]),
 'param_colsample_bytree': masked_array(data=[0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9,
                    0.9, 0.9, 0.9, 0.9, 0.9, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,
                    1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=1e+20),
 'param_learning_rate': masked_array(data=[0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.3, 0.3, 0.3,
                    0.3, 0.3, 0.3, 0.3, 0.3, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1,
                    0.1, 0.1, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=1e+20),
 'param_max_depth': masked_array(data=[9, 9, 9, 9, 12, 12, 12, 12, 9, 9, 9, 9, 12, 12, 12, 12,
                    9, 9, 9, 9, 12, 12, 12, 12, 9, 9, 9, 9, 12, 12, 12, 12],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_n_estimators': masked_array(data=[350, 350, 400, 400, 350, 350, 400, 400, 350, 350, 400,
                    400, 350, 350, 400, 400, 350, 350, 400, 400, 350, 350,
                    400, 400, 350, 350, 400, 400, 350, 350, 400, 400],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_subsample': masked_array(data=[0.8, 0.9, 0.8, 0.9, 0.8, 0.9, 0.8, 0.9, 0.8, 0.9, 0.8,
                    0.9, 0.8, 0.9, 0.8, 0.9, 0.8, 0.9, 0.8, 0.9, 0.8, 0.9,
                    0.8, 0.9, 0.8, 0.9, 0.8, 0.9, 0.8, 0.9, 0.8, 0.9],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=1e+20),
 'params': [{'colsample_bytree': 0.9,
   'learning_rate': 0.1,
   'max_depth': 9,
   'n_estimators': 350,
   'subsample': 0.8},
  {'colsample_bytree': 0.9,
   'learning_rate': 0.1,
   'max_depth': 9,
   'n_estimators': 350,
   'subsample': 0.9},
  {'colsample_bytree': 0.9,
   'learning_rate': 0.1,
   'max_depth': 9,
   'n_estimators': 400,
   'subsample': 0.8},
  {'colsample_bytree': 0.9,
   'learning_rate': 0.1,
   'max_depth': 9,
   'n_estimators': 400,
   'subsample': 0.9},
  {'colsample_bytree': 0.9,
   'learning_rate': 0.1,
   'max_depth': 12,
   'n_estimators': 350,
   'subsample': 0.8},
  {'colsample_bytree': 0.9,
   'learning_rate': 0.1,
   'max_depth': 12,
   'n_estimators': 350,
   'subsample': 0.9},
  {'colsample_bytree': 0.9,
   'learning_rate': 0.1,
   'max_depth': 12,
   'n_estimators': 400,
   'subsample': 0.8},
  {'colsample_bytree': 0.9,
   'learning_rate': 0.1,
   'max_depth': 12,
   'n_estimators': 400,
   'subsample': 0.9},
  {'colsample_bytree': 0.9,
   'learning_rate': 0.3,
   'max_depth': 9,
   'n_estimators': 350,
   'subsample': 0.8},
  {'colsample_bytree': 0.9,
   'learning_rate': 0.3,
   'max_depth': 9,
   'n_estimators': 350,
   'subsample': 0.9},
  {'colsample_bytree': 0.9,
   'learning_rate': 0.3,
   'max_depth': 9,
   'n_estimators': 400,
   'subsample': 0.8},
  {'colsample_bytree': 0.9,
   'learning_rate': 0.3,
   'max_depth': 9,
   'n_estimators': 400,
   'subsample': 0.9},
  {'colsample_bytree': 0.9,
   'learning_rate': 0.3,
   'max_depth': 12,
   'n_estimators': 350,
   'subsample': 0.8},
  {'colsample_bytree': 0.9,
   'learning_rate': 0.3,
   'max_depth': 12,
   'n_estimators': 350,
   'subsample': 0.9},
  {'colsample_bytree': 0.9,
   'learning_rate': 0.3,
   'max_depth': 12,
   'n_estimators': 400,
   'subsample': 0.8},
  {'colsample_bytree': 0.9,
   'learning_rate': 0.3,
   'max_depth': 12,
   'n_estimators': 400,
   'subsample': 0.9},
  {'colsample_bytree': 1,
   'learning_rate': 0.1,
   'max_depth': 9,
   'n_estimators': 350,
   'subsample': 0.8},
  {'colsample_bytree': 1,
   'learning_rate': 0.1,
   'max_depth': 9,
   'n_estimators': 350,
   'subsample': 0.9},
  {'colsample_bytree': 1,
   'learning_rate': 0.1,
   'max_depth': 9,
   'n_estimators': 400,
   'subsample': 0.8},
  {'colsample_bytree': 1,
   'learning_rate': 0.1,
   'max_depth': 9,
   'n_estimators': 400,
   'subsample': 0.9},
  {'colsample_bytree': 1,
   'learning_rate': 0.1,
   'max_depth': 12,
   'n_estimators': 350,
   'subsample': 0.8},
  {'colsample_bytree': 1,
   'learning_rate': 0.1,
   'max_depth': 12,
   'n_estimators': 350,
   'subsample': 0.9},
  {'colsample_bytree': 1,
   'learning_rate': 0.1,
   'max_depth': 12,
   'n_estimators': 400,
   'subsample': 0.8},
  {'colsample_bytree': 1,
   'learning_rate': 0.1,
   'max_depth': 12,
   'n_estimators': 400,
   'subsample': 0.9},
  {'colsample_bytree': 1,
   'learning_rate': 0.3,
   'max_depth': 9,
   'n_estimators': 350,
   'subsample': 0.8},
  {'colsample_bytree': 1,
   'learning_rate': 0.3,
   'max_depth': 9,
   'n_estimators': 350,
   'subsample': 0.9},
  {'colsample_bytree': 1,
   'learning_rate': 0.3,
   'max_depth': 9,
   'n_estimators': 400,
   'subsample': 0.8},
  {'colsample_bytree': 1,
   'learning_rate': 0.3,
   'max_depth': 9,
   'n_estimators': 400,
   'subsample': 0.9},
  {'colsample_bytree': 1,
   'learning_rate': 0.3,
   'max_depth': 12,
   'n_estimators': 350,
   'subsample': 0.8},
  {'colsample_bytree': 1,
   'learning_rate': 0.3,
   'max_depth': 12,
   'n_estimators': 350,
   'subsample': 0.9},
  {'colsample_bytree': 1,
   'learning_rate': 0.3,
   'max_depth': 12,
   'n_estimators': 400,
   'subsample': 0.8},
  {'colsample_bytree': 1,
   'learning_rate': 0.3,
   'max_depth': 12,
   'n_estimators': 400,
   'subsample': 0.9}],
 'split0_test_accuracy': array([0.99968454, 0.99969128, 0.99969128, 0.99969689, 0.99966433,
        0.99966882, 0.99966658, 0.99966995, 0.99966658, 0.99967893,
        0.99966546, 0.99967444, 0.99964525, 0.99966546, 0.99964974,
        0.99965984, 0.99968903, 0.99969577, 0.99968791, 0.99968903,
        0.99966658, 0.99967668, 0.99965984, 0.99967332, 0.99966882,
        0.99967219, 0.99967107, 0.99967444, 0.99964749, 0.99966097,
        0.99965086, 0.99966209]),
 'split1_test_accuracy': array([0.99968566, 0.99968342, 0.99967893, 0.99968454, 0.99967444,
        0.99966546, 0.99966321, 0.99965984, 0.9996576 , 0.99966433,
        0.99966097, 0.99966995, 0.99964862, 0.99963964, 0.9996576 ,
        0.999643  , 0.99967781, 0.99967781, 0.99967444, 0.99967893,
        0.9996677 , 0.99966658, 0.9996677 , 0.99966995, 0.99965423,
        0.99965311, 0.99964525, 0.99965872, 0.99964637, 0.999643  ,
        0.99964188, 0.99964188]),
 'split2_test_accuracy': array([0.99969128, 0.99969015, 0.99969128, 0.99968342, 0.99967444,
        0.99967668, 0.9996823 , 0.99967668, 0.99968005, 0.99967781,
        0.99967893, 0.99968791, 0.99966433, 0.99965984, 0.99966209,
        0.99966321, 0.99968791, 0.99968679, 0.9996924 , 0.99969465,
        0.99967556, 0.99966882, 0.99968342, 0.99966995, 0.99967107,
        0.99968005, 0.99967332, 0.99967556, 0.99966097, 0.99966658,
        0.99965648, 0.9996677 ]),
 'split3_test_accuracy': array([0.99968005, 0.99969128, 0.99968566, 0.99968679, 0.99966995,
        0.99966882, 0.99966658, 0.9996677 , 0.99966097, 0.99967556,
        0.99965872, 0.99966882, 0.9996677 , 0.99966433, 0.99965872,
        0.9996576 , 0.99967893, 0.99970026, 0.99967893, 0.99969577,
        0.99967219, 0.99967556, 0.99966882, 0.99967781, 0.99965872,
        0.99966658, 0.9996576 , 0.99966658, 0.99965984, 0.99965423,
        0.99965984, 0.99965423]),
 'split4_test_accuracy': array([0.99964974, 0.99964862, 0.99964525, 0.99964974, 0.99962841,
        0.99963627, 0.99962392, 0.99963627, 0.99962841, 0.99964188,
        0.99962055, 0.99964413, 0.99962392, 0.99962841, 0.99961718,
        0.99963178, 0.99964974, 0.99965311, 0.99964749, 0.99965648,
        0.9996329 , 0.99963851, 0.99963065, 0.99963065, 0.99962841,
        0.99964525, 0.99962729, 0.99964637, 0.9996228 , 0.99963851,
        0.99962167, 0.99963178]),
 'mean_test_accuracy': array([0.99967825, 0.99968095, 0.99967848, 0.99968028, 0.99966231,
        0.99966321, 0.99966052, 0.99966209, 0.99965872, 0.9996677 ,
        0.99965692, 0.99966905, 0.99964996, 0.99965154, 0.99964907,
        0.99965109, 0.99967668, 0.99968275, 0.99967623, 0.99968297,
        0.99966299, 0.99966523, 0.99966209, 0.99966433, 0.99965625,
        0.99966344, 0.9996549 , 0.99966433, 0.99964749, 0.99965266,
        0.99964615, 0.99965154]),
 'std_test_accuracy': array([1.46992937e-05, 1.64289256e-05, 1.72258190e-05, 1.59935615e-05,
        1.73541187e-05, 1.39677437e-05, 1.94653763e-05, 1.39857713e-05,
        1.69811735e-05, 1.39134921e-05, 1.94912577e-05, 1.41897323e-05,
        1.56429863e-05, 1.48527999e-05, 1.64473377e-05, 1.18681766e-05,
        1.42181344e-05, 1.67058089e-05, 1.57105208e-05, 1.45267912e-05,
        1.53830329e-05, 1.39026248e-05, 1.74641429e-05, 1.70847770e-05,
        1.52513753e-05, 1.26494974e-05, 1.71083380e-05, 1.08379991e-05,
        1.37494813e-05, 1.05695188e-05, 1.36648919e-05, 1.31420666e-05]),
 'rank_test_accuracy': array([ 6,  3,  5,  4, 17, 15, 20, 18, 21, 10, 22,  9, 29, 27, 30, 28,  7,
         2,  8,  1, 16, 11, 19, 13, 23, 14, 24, 12, 31, 25, 32, 26]),
 'split0_test_balanced_accuracy': array([0.90822153, 0.9082249 , 0.91213288, 0.90996459, 0.90560609,
        0.906911  , 0.90908098, 0.90951688, 0.90994942, 0.91473203,
        0.91038307, 0.91472978, 0.90689919, 0.9108173 , 0.9082041 ,
        0.9090776 , 0.91213176, 0.91083247, 0.9121312 , 0.91039488,
        0.90994942, 0.90778337, 0.90951182, 0.90778169, 0.91212164,
        0.91646554, 0.91212277, 0.91603244, 0.90733454, 0.91211771,
        0.90863889, 0.91255249]),
 'split1_test_balanced_accuracy': array([0.90735365, 0.90604986, 0.9077845 , 0.90822153, 0.90995335,
        0.90734353, 0.90951351, 0.90864338, 0.9095107 , 0.91472472,
        0.91081505, 0.91603019, 0.91080886, 0.90819905, 0.91341868,
        0.90993761, 0.90691549, 0.90604705, 0.90734803, 0.9077845 ,
        0.9082131 , 0.90777831, 0.90994998, 0.90908266, 0.91254856,
        0.90907423, 0.9112414 , 0.91255081, 0.90689976, 0.90950339,
        0.90733173, 0.91123971]),
 'split2_test_balanced_accuracy': array([0.9082249 , 0.90865856, 0.90952756, 0.90778674, 0.90821647,
        0.90908603, 0.91082573, 0.9103887 , 0.91169304, 0.91038926,
        0.91256092, 0.91299964, 0.91125095, 0.91038026, 0.91211827,
        0.91255305, 0.90778899, 0.90952531, 0.91083078, 0.91170035,
        0.90951969, 0.906911  , 0.91212895, 0.90864844, 0.91385965,
        0.91473259, 0.91429499, 0.91516456, 0.90820972, 0.91125208,
        0.90777326, 0.91212108]),
 'split3_test_balanced_accuracy': array([0.90517973, 0.90692224, 0.90648521, 0.90691999, 0.90343779,
        0.90473989, 0.90473877, 0.90517355, 0.90430174, 0.90995391,
        0.90430061, 0.90777944, 0.9082131 , 0.90994829, 0.90777438,
        0.90777382, 0.90474495, 0.9082294 , 0.90561339, 0.90822715,
        0.90561002, 0.90474327, 0.90517411, 0.90648127, 0.90560328,
        0.90690987, 0.90516849, 0.90864675, 0.9069065 , 0.90864057,
        0.90647228, 0.90994323]),
 'split4_test_balanced_accuracy': array([0.89595549, 0.89638953, 0.89551864, 0.89725929, 0.89377182,
        0.89377575, 0.89333497, 0.89507955, 0.898987  , 0.90203594,
        0.89767927, 0.90290626, 0.89637716, 0.8994216 , 0.89506999,
        0.89942329, 0.89595549, 0.89769557, 0.89769276, 0.89900105,
        0.89333947, 0.89681907, 0.89290374, 0.89464214, 0.9024638 ,
        0.90247223, 0.90115944, 0.90508038, 0.8963766 , 0.90290345,
        0.89681064, 0.90116168]),
 'mean_test_balanced_accuracy': array([0.90498706, 0.90524902, 0.90628976, 0.90603043, 0.9041971 ,
        0.90437124, 0.90549879, 0.90576041, 0.90688838, 0.91036717,
        0.90714779, 0.91088906, 0.90670985, 0.9077533 , 0.90731709,
        0.90775308, 0.90550734, 0.90646596, 0.90672323, 0.90742159,
        0.90532634, 0.904807  , 0.90593372, 0.90532724, 0.90931938,
        0.90993089, 0.90879742, 0.91149499, 0.90514542, 0.90888344,
        0.90540536, 0.90940364]),
 'std_test_balanced_accuracy': array([0.00465086, 0.00452576, 0.00570815, 0.00449639, 0.00566636,
        0.00547566, 0.00641658, 0.00562617, 0.00465733, 0.00463941,
        0.00549504, 0.00487917, 0.00541264, 0.00425964, 0.00650028,
        0.00444864, 0.00534586, 0.00466114, 0.00508507, 0.00444599,
        0.00618152, 0.00414549, 0.00689451, 0.00541592, 0.00446548,
        0.00512347, 0.00487365, 0.00410922, 0.00441029, 0.0032334 ,
        0.00435387, 0.00421644]),
 'rank_test_balanced_accuracy': array([29, 27, 18, 19, 32, 31, 23, 21, 14,  3, 13,  2, 16,  9, 12, 10, 22,
        17, 15, 11, 26, 30, 20, 25,  6,  4,  8,  1, 28,  7, 24,  5]),
 'split0_test_f1': array([0.86984715, 0.87227125, 0.87333026, 0.87476809, 0.86189376,
        0.8638671 , 0.86369894, 0.86501377, 0.86394869, 0.86964448,
        0.86367795, 0.86806187, 0.85557587, 0.86380256, 0.85753425,
        0.86132723, 0.87252646, 0.87459509, 0.87212511, 0.87205543,
        0.86394869, 0.86691312, 0.86145405, 0.86571297, 0.86535828,
        0.86775362, 0.86614893, 0.86842105, 0.85648995, 0.86260237,
        0.85805568, 0.8631196 ]),
 'split1_test_f1': array([0.87000929, 0.86883721, 0.86771508, 0.86984715, 0.86672794,
        0.86279926, 0.86263736, 0.86120018, 0.86066697, 0.86452198,
        0.86222628, 0.86684783, 0.85792102, 0.85402456, 0.86180335,
        0.85571688, 0.86706809, 0.86682135, 0.86598891, 0.86771508,
        0.86384545, 0.8633226 , 0.86434464, 0.86488971, 0.86038078,
        0.85896851, 0.85688406, 0.86194369, 0.85596708, 0.85558583,
        0.85453716, 0.85572139]),
 'split2_test_f1': array([0.87227125, 0.87198516, 0.87262622, 0.86932345, 0.86623616,
        0.86728111, 0.8697653 , 0.86764706, 0.86920606, 0.86804598,
        0.86904762, 0.87235996, 0.86353263, 0.86170698, 0.86299499,
        0.86351228, 0.87093779, 0.87101248, 0.87338262, 0.8744229 ,
        0.86700414, 0.8638671 , 0.87052342, 0.86476541, 0.86663632,
        0.87004104, 0.86754665, 0.86857663, 0.86146789, 0.86432161,
        0.85976169, 0.8649635 ]),
 'split3_test_f1': array([0.86738018, 0.8719143 , 0.86976744, 0.87029289, 0.86325581,
        0.86323598, 0.86243631, 0.86296296, 0.86031452, 0.86712644,
        0.85951941, 0.86411792, 0.86384545, 0.86315789, 0.86055046,
        0.86015589, 0.86685289, 0.87552448, 0.86710037, 0.87389483,
        0.86468953, 0.86564389, 0.86336267, 0.86694483, 0.85990783,
        0.86307054, 0.8593822 , 0.86357373, 0.86068966, 0.85923218,
        0.86056144, 0.85961714]),
 'split4_test_f1': array([0.85365854, 0.85339578, 0.85192127, 0.85406922, 0.84539935,
        0.84817245, 0.84367709, 0.84859813, 0.84711316, 0.85279188,
        0.84395199, 0.8538497 , 0.8446917 , 0.84725427, 0.84191006,
        0.84842884, 0.85365854, 0.85540477, 0.85340803, 0.85700935,
        0.84683841, 0.8499534 , 0.84590164, 0.8464769 , 0.84823475,
        0.85410896, 0.84742647, 0.85530547, 0.84430028, 0.85188592,
        0.84405368, 0.84898711]),
 'mean_test_f1': array([0.86663328, 0.86768074, 0.86707205, 0.86766016, 0.86070261,
        0.86107118, 0.860443  , 0.86108442, 0.86024988, 0.86442615,
        0.85968465, 0.86504746, 0.85711333, 0.85798925, 0.85695862,
        0.85782822, 0.86620875, 0.86867163, 0.86640101, 0.86901952,
        0.86126524, 0.86194002, 0.86111728, 0.86175796, 0.86010359,
        0.86278853, 0.85947766, 0.86356411, 0.85578297, 0.85872558,
        0.85539393, 0.85848175]),
 'std_test_f1': array([0.00666956, 0.0072515 , 0.00783886, 0.00706706, 0.00786196,
        0.00663973, 0.00880217, 0.00660239, 0.00730268, 0.00604965,
        0.00845713, 0.00619765, 0.00698344, 0.00640765, 0.00774081,
        0.0053437 , 0.00664738, 0.007307  , 0.00708498, 0.00645179,
        0.00730278, 0.00612788, 0.00819222, 0.00767996, 0.00650035,
        0.00578374, 0.007233  , 0.00488971, 0.00614459, 0.00454402,
        0.00603657, 0.00570227]),
 'rank_test_f1': array([ 6,  3,  5,  4, 19, 18, 20, 17, 21, 10, 23,  9, 29, 27, 30, 28,  8,
         2,  7,  1, 15, 13, 16, 14, 22, 12, 24, 11, 31, 25, 32, 26]),
 'split0_test_precision': array([0.93062438, 0.93619143, 0.92850147, 0.93737575, 0.91921182,
        0.92035398, 0.91448008, 0.91634241, 0.91287512, 0.9137931 ,
        0.91119691, 0.91030534, 0.9017341 , 0.91040462, 0.90288462,
        0.90917874, 0.92668622, 0.9347181 , 0.92578125, 0.93004926,
        0.91287512, 0.92504931, 0.90838959, 0.92232055, 0.91066282,
        0.90548204, 0.91241578, 0.90796964, 0.9026975 , 0.90458015,
        0.90297791, 0.90467112]),
 'split1_test_precision': array([0.93326693, 0.934     , 0.92687747, 0.93062438, 0.91910331,
        0.91682975, 0.91102515, 0.90997096, 0.906641  , 0.9025544 ,
        0.90690979, 0.90453686, 0.8974359 , 0.89513823, 0.89971618,
        0.89468691, 0.92765114, 0.92935323, 0.92406312, 0.92687747,
        0.91699219, 0.91691105, 0.91375969, 0.917154  , 0.89867424,
        0.90393852, 0.89413989, 0.90209125, 0.90260366, 0.89543726,
        0.89837009, 0.89161169]),
 'split2_test_precision': array([0.93619143, 0.93439364, 0.93359762, 0.93055556, 0.92239686,
        0.92254902, 0.92375367, 0.92007797, 0.92031098, 0.92097561,

In [37]:
grid_search.best_index_

19